<?php
return array(
    'adminName'=>'内容管理系统',
    'webName'=>'KaayStudio',
    'QiniuHost'=>'http://plf4ebg8o.bkt.clouddn.com/',
//    'domain'=>'http://'.$_SERVER['SERVER_NAME'],
//    'image_host'=>'http://'.$_SERVER['SERVER_NAME'],
    'categoryType'=>array(
        'images'=>'图片模型',
        'posts'=>'文章模型',
        'page'=>'单页模型',
        'url'=>'外部链接',
    ),
    'linksType'=>array(
        1=>'综合网站',
        2=>'社交娱乐',
        3=>'生活服务'
    ),
    'bannersClient'=>array(
        'pc'=>'PC端',
        'app'=>'App端',
    ),
    'bannersLocation'=>array(
        'index'=>'首页',
        'posts'=>'栏目页',
        'details'=>'内容页'
    ),
    'Icons'=>array(
        'am-icon-qq',
        'am-icon-weibo',
        'am-icon-weixin',
        'am-icon-tencent-weibo',
        'am-icon-twitter',
        'am-icon-facebook',
        'am-icon-facebook-square',
        'am-icon-twitter',
        'am-icon-twitter-square',
        'am-icon-google-plus-square',
        'am-icon-youtube',
        'am-icon-youtube-square',
        'am-icon-instagram'
    )
);