<?php
return array(
    array(
        'name'=>'管理员管理',
        'controller'=>'sellers',
        'icons'=>'icon-users',
        'element'=>
            array(
                'admins'=>'管理员列表|/seller/admins/list',
            ),
    ),
    array(
        'name'=>'栏目管理',
        'controller'=>'category',
        'icons'=>'icon-press',
        'element'=>
            array(
                'category'=>'栏目列表|/seller/category/list',
            ),
    ),
    array(
        'name'=>'内容管理',
        'controller'=>'posts',
        'icons'=>'icon-press',
        'element'=>
            array(
                'posts'=>'',
            ),
    ),
    array(
        'name'=>'Logo管理',
        'controller'=>'logo',
        'icons'=>'icon-press',
        'element'=>
            array(
                'logo'=>'Logo管理|/seller/logo/list',
            ),
    ),
    array(
        'name'=>'友链管理',
        'controller'=>'links',
        'icons'=>'icon-press',
        'element'=>
            array(
                'links'=>'友链列表|/seller/links/list',
            ),
    ),
    array(
        'name'=>'广告管理',
        'controller'=>'banners',
        'icons'=>'icon-press',
        'element'=>
            array(
                'banners'=>'广告列表|/seller/banners/list',
            ),
    ),
);
